
// This file has been generated by the GUI designer. Do not modify.
namespace Gebat
{
	public partial class Passwd
	{
		private global::Gtk.Fixed fixed4;
		private global::Gtk.Label label7;
		private global::Gtk.Entry entry6;
		private global::Gtk.Button button4;
		private global::Gtk.Label label8;
		private global::Gtk.Button button3;
		private global::Gtk.Button button5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gebat.Passwd
			this.Name = "Gebat.Passwd";
			this.Title = global::Mono.Unix.Catalog.GetString ("Contraseña");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Gebat.Passwd.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña: ");
			this.fixed4.Add (this.label7);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label7]));
			w1.X = 18;
			w1.Y = 109;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.Visibility = false;
			this.entry6.InvisibleChar = '●';
			this.fixed4.Add (this.entry6);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.entry6]));
			w2.X = 111;
			w2.Y = 104;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Conectar");
			this.fixed4.Add (this.button4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button4]));
			w3.X = 189;
			w3.Y = 147;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.fixed4.Add (this.label8);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label8]));
			w4.X = 142;
			w4.Y = 188;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.Sensitive = false;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.fixed4.Add (this.button3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button3]));
			w5.X = 258;
			w5.Y = 255;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.fixed4.Add (this.button5);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button5]));
			w6.X = 334;
			w6.Y = 255;
			this.Add (this.fixed4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.button4.Clicked += new global::System.EventHandler (this.connect);
			this.button3.Clicked += new global::System.EventHandler (this.accept);
			this.button5.Clicked += new global::System.EventHandler (this.exit);
		}
	}
}
