
// This file has been generated by the GUI designer. Do not modify.
namespace Gebat
{
	public partial class FoodManager
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Fixed fixedQuantity;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.ComboBox comboboxType;
		private global::Gtk.SpinButton spinbuttonQuantity;
		private global::Gtk.Entry entryName;
		private global::Gtk.Button buttonAccept;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label1;
		private global::Gtk.Entry entrySearch;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewFood;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button buttonDelete;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gebat.FoodManager
			this.Name = "Gebat.FoodManager";
			this.Title = global::Mono.Unix.Catalog.GetString ("FoodManager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Gebat.FoodManager.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixedQuantity = new global::Gtk.Fixed ();
			this.fixedQuantity.Name = "fixedQuantity";
			this.fixedQuantity.HasWindow = false;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre: ");
			this.fixedQuantity.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.label2]));
			w1.X = 4;
			w1.Y = 83;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Cantidad: ");
			this.fixedQuantity.Add (this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.label3]));
			w2.X = 4;
			w2.Y = 157;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo de cantidad: ");
			this.fixedQuantity.Add (this.label4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.label4]));
			w3.X = 7;
			w3.Y = 239;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.comboboxType = global::Gtk.ComboBox.NewText ();
			this.comboboxType.Name = "comboboxType";
			this.fixedQuantity.Add (this.comboboxType);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.comboboxType]));
			w4.X = 133;
			w4.Y = 231;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.spinbuttonQuantity = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbuttonQuantity.CanFocus = true;
			this.spinbuttonQuantity.Name = "spinbuttonQuantity";
			this.spinbuttonQuantity.Adjustment.PageIncrement = 10;
			this.spinbuttonQuantity.ClimbRate = 1;
			this.spinbuttonQuantity.Numeric = true;
			this.fixedQuantity.Add (this.spinbuttonQuantity);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.spinbuttonQuantity]));
			w5.X = 132;
			w5.Y = 150;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.entryName = new global::Gtk.Entry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.fixedQuantity.Add (this.entryName);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.entryName]));
			w6.X = 128;
			w6.Y = 75;
			// Container child fixedQuantity.Gtk.Fixed+FixedChild
			this.buttonAccept = new global::Gtk.Button ();
			this.buttonAccept.CanFocus = true;
			this.buttonAccept.Name = "buttonAccept";
			this.buttonAccept.UseUnderline = true;
			// Container child buttonAccept.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.buttonAccept.Add (w7);
			this.fixedQuantity.Add (this.buttonAccept);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuantity [this.buttonAccept]));
			w15.X = 126;
			w15.Y = 337;
			this.hbox1.Add (this.fixedQuantity);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixedQuantity]));
			w16.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Buscar: ");
			this.hbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry ();
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hbox3.Add (this.entrySearch);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entrySearch]));
			w18.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewFood = new global::Gtk.TreeView ();
			this.treeviewFood.CanFocus = true;
			this.treeviewFood.Name = "treeviewFood";
			this.GtkScrolledWindow.Add (this.treeviewFood);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w21.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.Sensitive = false;
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			// Container child buttonDelete.Gtk.Container+ContainerChild
			global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w23 = new global::Gtk.HBox ();
			w23.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w23.Add (w24);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.LabelProp = global::Mono.Unix.Catalog.GetString ("Eliminar");
			w26.UseUnderline = true;
			w23.Add (w26);
			w22.Add (w23);
			this.buttonDelete.Add (w22);
			this.hbox2.Add (this.buttonDelete);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonDelete]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w32.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 717;
			this.DefaultHeight = 544;
			this.Show ();
			this.comboboxType.Changed += new global::System.EventHandler (this.quantityChanged);
			this.buttonAccept.Clicked += new global::System.EventHandler (this.insertFood);
			this.entrySearch.Changed += new global::System.EventHandler (this.searchFood);
			this.treeviewFood.CursorChanged += new global::System.EventHandler (this.treefoodchanged);
			this.buttonDelete.Clicked += new global::System.EventHandler (this.deletefood);
		}
	}
}
