//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GebatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiar : Person
    {
        public int Id { get; private set; }
        public int Income { get; set; }
        private int PersonalDossierId { get; set; }
    
        public virtual PersonalDossier PersonalDossier { get; private set; }
    }
}
