//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GebatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.EntryFood = new HashSet<EntryFood>();
            this.OutgoingFood = new HashSet<OutgoingFood>();
        }
    
        public int IdFood { get; private set; }
        public string Name { get; set; }
        public int Quantity { get; private set; }
        private int TypeIdType { get; set; }
        private int ConcessionTypeIdConcessionType { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual ICollection<EntryFood> EntryFood { get; private set; }
        public virtual ICollection<OutgoingFood> OutgoingFood { get; set; }
        public virtual ConcessionType ConcessionType { get; set; }
    }
}
