//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GebatModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GebatDataBaseEntities : DbContext
    {
        public GebatDataBaseEntities()
            : base("name=GebatDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<EntryFood> EntryFood { get; set; }
        public virtual DbSet<OutgoingFood> OutgoingFood { get; set; }
        public virtual DbSet<Concession> Concession { get; set; }
        public virtual DbSet<ConcessionType> ConcessionType { get; set; }
        public virtual DbSet<DateRestriction> DateRestriction { get; set; }
        public virtual DbSet<PersonalDossier> PersonalDossier { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    }
}
