//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GebatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC : Person
    {
        public string Court { get; set; }
        public string Judgement { get; set; }
        public System.DateTime BeginDate { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public string BeginHour { get; set; }
        public string FinishHour { get; set; }
        public System.DateTime FinishDate { get; set; }
        private int CrimeId { get; set; }
    
        public virtual Crime Crime { get; set; }
    }
}
